[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-image-optim"

[functions]
  external_node_modules = ["@node-rs/*"]
  included_files = ["node_modules/@node-rs/**/*"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# サイトマップのContent-Type設定
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

# robots.txtのContent-Type設定
[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

# コース詳細ページへのリダイレクト
[[redirects]]
  from = "/courses/ai-art"
  to = "/courses/ai-art/index.html"
  status = 200

[[redirects]]
  from = "/courses/game-creator"
  to = "/courses/game-creator/index.html"
  status = 200

[[redirects]]
  from = "/courses/app-dev"
  to = "/courses/app-dev/index.html"
  status = 200

[[redirects]]
  from = "/courses/music"
  to = "/courses/music/index.html"
  status = 200

[[redirects]]
  from = "/courses/robotics"
  to = "/courses/robotics/index.html"
  status = 200

[[redirects]]
  from = "/courses/video"
  to = "/courses/video/index.html"
  status = 200

# その他のページは通常のSPAリダイレクト
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200